In [2]:
import pandas as pd
import polars as pl

Cleaning strategy for NPPES file:
- read in only columns relevant to this project
- process taxonomy code columns to determine primary
- drop taxonomy code columns (keep only added primary code column)
- make column names better for SQL
- join classification crosswalk to get taxonomy name
- join CBSA crosswalk to match provider on zip code

In [64]:
# generate list of taxonomy columns
tax_cols = []

for i in range(1, 16):
    switch_col_name = f'Healthcare Provider Primary Taxonomy Switch_{i}'
    tax_cols.append(switch_col_name)
    code_col_name = f'Healthcare Provider Taxonomy Code_{i}'
    tax_cols.append(code_col_name)

# other relevant columns
cols = ['NPI', 'Entity Type Code', 'Provider Organization Name (Legal Business Name)', 'Provider Last Name (Legal Name)',
        'Provider First Name', 'Provider Middle Name', 'Provider Name Prefix Text', 'Provider Name Suffix Text',
        'Provider Credential Text', 'Provider First Line Business Practice Location Address',
        'Provider Second Line Business Practice Location Address', 'Provider Business Practice Location Address City Name',
        'Provider Business Practice Location Address State Name', 'Provider Business Practice Location Address Postal Code']

# combine column name lists
cols.extend(tax_cols)

In [71]:
npi = pd.read_csv('../data/npidata_pfile_20050523-20240211.csv', usecols = cols)

/var/folders/xm/vmtk5pms0jzb2kmtm00lwtn80000gn/T/ipykernel_36556/1476842930.py:1: DtypeWarning: Columns (32,67,70,71,74,75,78,79,82,83,86,87,90,91,94,95,98,99,102,103,106) have mixed types. Specify dtype option on import or set low_memory=False.
  npi = pd.read_csv('../data/npidata_pfile_20050523-20240211.csv', usecols = cols)

In [66]:
# modify read in to get necessary columns and rename at the same time
npi.head()

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,Provider First Line Business Practice Location Address,...,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15
0,1679576722,1.0,NaN,WIEBE,DAVID,A,NaN,NaN,M.D.,3500 CENTRAL AVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1588667638,1.0,NaN,PILCHER,WILLIAM,C,DR.,NaN,MD,1824 KING STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1497758544,2.0,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN,NaN,NaN,NaN,NaN,NaN,3418 VILLAGE DR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1306849450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1215930367,1.0,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,M.D.,17323 RED OAK DR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
# pull primary taxonomy codes into one column
def extract_taxonomy_code(row):

    for i in range(1, 16):
        switch_col_name = f'Healthcare Provider Primary Taxonomy Switch_{i}'
        if row[switch_col_name] == 'Y':
            code_col_name = f'Healthcare Provider Taxonomy Code_{i}'
            return row[code_col_name]
    
    return None # catch columns with no 'Y' switch

In [74]:
npi['extracted_taxonomy_code'] = npi.apply(extract_taxonomy_code, axis = 1)

In [70]:
npi.info()
# having doublechecked the values in the switch columns, it appears that there are rows with no 'Y' switch
# should those rows be dropped, or possibly the taxonomy code in Code_1 could be inferred to be the correct code?
# some rows with no 'Y' switch have one or more 'X' switches

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 45 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   NPI                                                      1000 non-null   int64
 1   Entity Type Code                                         930 non-null    float64
 2   Provider Organization Name (Legal Business Name)         188 non-null    object
 3   Provider Last Name (Legal Name)                          742 non-null    object
 4   Provider First Name                                      742 non-null    object
 5   Provider Middle Name                                     585 non-null    object
 6   Provider Name Prefix Text                                470 non-null    object
 7   Provider Name Suffix Text                                27 non-null     object
 8   Provider Credential Text                                 728 non-null    object
 9   Provider First Line Business Practice Location Address   930 non-null    object
 10  Provider Second Line Business Practice Location Address  370 non-null    object
 11  Provider Business Practice Location Address City Name    930 non-null    object
 12  Provider Business Practice Location Address State Name   930 non-null    object
 13  Provider Business Practice Location Address Postal Code  930 non-null    float64
 14  Healthcare Provider Taxonomy Code_1                      930 non-null    object
 15  Healthcare Provider Primary Taxonomy Switch_1            930 non-null    object
 16  Healthcare Provider Taxonomy Code_2                      255 non-null    object
 17  Healthcare Provider Primary Taxonomy Switch_2            255 non-null    object
 18  Healthcare Provider Taxonomy Code_3                      58 non-null     object
 19  Healthcare Provider Primary Taxonomy Switch_3            58 non-null     object
 20  Healthcare Provider Taxonomy Code_4                      23 non-null     object
 21  Healthcare Provider Primary Taxonomy Switch_4            23 non-null     object
 22  Healthcare Provider Taxonomy Code_5                      13 non-null     object
 23  Healthcare Provider Primary Taxonomy Switch_5            13 non-null     object
 24  Healthcare Provider Taxonomy Code_6                      10 non-null     object
 25  Healthcare Provider Primary Taxonomy Switch_6            10 non-null     object
 26  Healthcare Provider Taxonomy Code_7                      6 non-null      object
 27  Healthcare Provider Primary Taxonomy Switch_7            6 non-null      object
 28  Healthcare Provider Taxonomy Code_8                      6 non-null      object
 29  Healthcare Provider Primary Taxonomy Switch_8            6 non-null      object
 30  Healthcare Provider Taxonomy Code_9                      4 non-null      object
 31  Healthcare Provider Primary Taxonomy Switch_9            4 non-null      object
 32  Healthcare Provider Taxonomy Code_10                     2 non-null      object
 33  Healthcare Provider Primary Taxonomy Switch_10           2 non-null      object
 34  Healthcare Provider Taxonomy Code_11                     1 non-null      object
 35  Healthcare Provider Primary Taxonomy Switch_11           1 non-null      object
 36  Healthcare Provider Taxonomy Code_12                     1 non-null      object
 37  Healthcare Provider Primary Taxonomy Switch_12           1 non-null      object
 38  Healthcare Provider Taxonomy Code_13                     1 non-null      object
 39  Healthcare Provider Primary Taxonomy Switch_13           1 non-null      object
 40  Healthcare Provider Taxonomy Code_14                     0 non-null      float64
 41  Healthcare Provider Primary Taxonomy Switch_14           0 non-null      float64
 42  Healthcare Provider Taxonomy Code_15                     0 non-null      float64
 43  Healthcare Provider Primary Taxonomy Switch_15           0 non-null      float64
 44  extracted_taxonomy_code                                  920 non-null    object
dtypes: float64(6), int64(1), object(38)
memory usage: 351.7+ KB

In [48]:
# if we decide to drop rows with no 'Y' switch
taxonomy.dropna(subset = ['extracted_taxonomy_code'], inplace = True)

In [60]:
taxonomy.iloc[43]

Healthcare Provider Primary Taxonomy Switch_1              X
Healthcare Provider Primary Taxonomy Switch_2              X
Healthcare Provider Primary Taxonomy Switch_3              X
Healthcare Provider Primary Taxonomy Switch_4              X
Healthcare Provider Primary Taxonomy Switch_5            NaN
Healthcare Provider Primary Taxonomy Switch_6            NaN
Healthcare Provider Primary Taxonomy Switch_7            NaN
Healthcare Provider Primary Taxonomy Switch_8            NaN
Healthcare Provider Primary Taxonomy Switch_9            NaN
Healthcare Provider Primary Taxonomy Switch_10           NaN
Healthcare Provider Primary Taxonomy Switch_11           NaN
Healthcare Provider Primary Taxonomy Switch_12           NaN
Healthcare Provider Primary Taxonomy Switch_13           NaN
Healthcare Provider Primary Taxonomy Switch_14           NaN
Healthcare Provider Primary Taxonomy Switch_15           NaN
Healthcare Provider Taxonomy Code_1               103TC0700X
Healthcare Provider Taxonomy Code_2               103TC2200X
Healthcare Provider Taxonomy Code_3               103TF0000X
Healthcare Provider Taxonomy Code_4               103T00000X
Healthcare Provider Taxonomy Code_5                      NaN
Healthcare Provider Taxonomy Code_6                      NaN
Healthcare Provider Taxonomy Code_7                      NaN
Healthcare Provider Taxonomy Code_8                      NaN
Healthcare Provider Taxonomy Code_9                      NaN
Healthcare Provider Taxonomy Code_10                     NaN
Healthcare Provider Taxonomy Code_11                     NaN
Healthcare Provider Taxonomy Code_12                     NaN
Healthcare Provider Taxonomy Code_13                     NaN
Healthcare Provider Taxonomy Code_14                     NaN
Healthcare Provider Taxonomy Code_15                     NaN
extracted_taxonomy_code                                 None
Name: 43, dtype: object